### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by benytocarlo** [papermoon1978/atom-justify#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-justify](https://github.com/papermoon1978/atom-justify) package, v0.4.1
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/Mac/.atom/packages/atom-justify/lib/atom-justify-actions.coffee:6

TypeError: undefined is not a function
  at Function.module.exports.AtomJustifyActions.createSelection (/Users/Mac/.atom/packages/atom-justify/lib/atom-justify-actions.coffee:6:33)
  at Object.module.exports.AtomJustify.createSelection (/Users/Mac/.atom/packages/atom-justify/lib/atom-justify.coffee:21:28)
  at atom-workspace.subscriptions.add.atom.commands.add.atom-justify:createSelection (/Users/Mac/.atom/packages/atom-justify/lib/atom-justify.coffee:11:100)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```
### Commands

```
     -1:35.4.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -1:12.6.0 pane:split-right (atom-text-editor.editor.is-focused)
     -1:02.4.0 window:focus-pane-below (atom-text-editor.editor.is-focused)
     -0:51.8.0 window:decrease-font-size (atom-text-editor.editor.is-focused)
     -0:48.4.0 find-and-replace:toggle (atom-text-editor.editor.is-focused)
     -0:45.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:45.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:44.3.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:43.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:43.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:37.4.0 editor:toggle-soft-wrap (atom-text-editor.editor.is-focused)
  2x -0:27.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.3.0 tree-view:toggle-focus (atom-text-editor.editor.is-focused)
     -0:01.5.0 atom-justify:createSelection (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-justify, v0.4.1
atom-minify, v0.1.6
atom-spotify2, v2.1.2
minimap, v4.10.0
minimap-git-diff, v4.1.3

# Dev
No dev packages
```

**Comment by JustinAiken** [comment]
Getting the same w/ Atom 1.0.2

**Comment by j-walker23** [comment]
and 1.0.3
